services:
  kindle-clock:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "REDIS_URL=redis:6379"
      - "AWAIR_OAUTH_TOKEN=${AWAIR_OAUTH_TOKEN}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - redis
  redis:
    image: "redis:7"
    ports:
      - "6379:6379"
