// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"context"
	"github.com/y-yu/kindle-clock-go/domain"
	"github.com/y-yu/kindle-clock-go/domain/repository"
	"github.com/y-yu/kindle-clock-go/infra/api"
	"github.com/y-yu/kindle-clock-go/infra/cache"
	repository2 "github.com/y-yu/kindle-clock-go/repository"
)

// Injectors from wire.go:

func Initialize(ctx context.Context) repository.AwairRepository {
	awairApiClient := api.NewAwairApiClient(ctx)
	cacheClient := cache.NewAwairCacheClient(ctx)
	systemClock := domain.NewSystemClock()
	awairRepository := repository2.NewAwairRepository(ctx, awairApiClient, cacheClient, systemClock)
	return awairRepository
}
