// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: infra/cache/proto/awair.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AwairDataModel struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Score                 int32                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Temperature           float32                `protobuf:"fixed32,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity              float32                `protobuf:"fixed32,3,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Co2                   int32                  `protobuf:"varint,4,opt,name=co2,proto3" json:"co2,omitempty"`
	Voc                   int32                  `protobuf:"varint,5,opt,name=voc,proto3" json:"voc,omitempty"`
	Pm25                  float32                `protobuf:"fixed32,6,opt,name=pm25,proto3" json:"pm25,omitempty"`
	CreatedAtMilliseconds int64                  `protobuf:"varint,7,opt,name=created_at_milliseconds,json=createdAtMilliseconds,proto3" json:"created_at_milliseconds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AwairDataModel) Reset() {
	*x = AwairDataModel{}
	mi := &file_infra_cache_proto_awair_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwairDataModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwairDataModel) ProtoMessage() {}

func (x *AwairDataModel) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cache_proto_awair_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwairDataModel.ProtoReflect.Descriptor instead.
func (*AwairDataModel) Descriptor() ([]byte, []int) {
	return file_infra_cache_proto_awair_proto_rawDescGZIP(), []int{0}
}

func (x *AwairDataModel) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *AwairDataModel) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *AwairDataModel) GetHumidity() float32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *AwairDataModel) GetCo2() int32 {
	if x != nil {
		return x.Co2
	}
	return 0
}

func (x *AwairDataModel) GetVoc() int32 {
	if x != nil {
		return x.Voc
	}
	return 0
}

func (x *AwairDataModel) GetPm25() float32 {
	if x != nil {
		return x.Pm25
	}
	return 0
}

func (x *AwairDataModel) GetCreatedAtMilliseconds() int64 {
	if x != nil {
		return x.CreatedAtMilliseconds
	}
	return 0
}

var File_infra_cache_proto_awair_proto protoreflect.FileDescriptor

var file_infra_cache_proto_awair_proto_rawDesc = string([]byte{
	0x0a, 0x1d, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x77, 0x61, 0x69, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x21, 0x6b, 0x69, 0x6e, 0x64, 0x6c, 0x65, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x69, 0x6e, 0x66,
	0x72, 0x61, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x61, 0x77, 0x61,
	0x69, 0x72, 0x22, 0xd4, 0x01, 0x0a, 0x0e, 0x41, 0x77, 0x61, 0x69, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74,
	0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x68, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x08, 0x68, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6f, 0x32,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x6f, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x76,
	0x6f, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x76, 0x6f, 0x63, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x6d, 0x32, 0x35, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x70, 0x6d, 0x32,
	0x35, 0x12, 0x36, 0x0a, 0x17, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x5f,
	0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x15, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x4d, 0x69, 0x6c,
	0x6c, 0x69, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x2d, 0x79, 0x75, 0x2f, 0x6b, 0x69, 0x6e,
	0x64, 0x6c, 0x65, 0x2d, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_infra_cache_proto_awair_proto_rawDescOnce sync.Once
	file_infra_cache_proto_awair_proto_rawDescData []byte
)

func file_infra_cache_proto_awair_proto_rawDescGZIP() []byte {
	file_infra_cache_proto_awair_proto_rawDescOnce.Do(func() {
		file_infra_cache_proto_awair_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_infra_cache_proto_awair_proto_rawDesc), len(file_infra_cache_proto_awair_proto_rawDesc)))
	})
	return file_infra_cache_proto_awair_proto_rawDescData
}

var file_infra_cache_proto_awair_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_infra_cache_proto_awair_proto_goTypes = []any{
	(*AwairDataModel)(nil), // 0: kindleclock.infra.datamodel.awair.AwairDataModel
}
var file_infra_cache_proto_awair_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_infra_cache_proto_awair_proto_init() }
func file_infra_cache_proto_awair_proto_init() {
	if File_infra_cache_proto_awair_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infra_cache_proto_awair_proto_rawDesc), len(file_infra_cache_proto_awair_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_infra_cache_proto_awair_proto_goTypes,
		DependencyIndexes: file_infra_cache_proto_awair_proto_depIdxs,
		MessageInfos:      file_infra_cache_proto_awair_proto_msgTypes,
	}.Build()
	File_infra_cache_proto_awair_proto = out.File
	file_infra_cache_proto_awair_proto_goTypes = nil
	file_infra_cache_proto_awair_proto_depIdxs = nil
}
