// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: infra/cache/proto/switchbot.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SwitchBotDevicesDataModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*SwitchBotDevice     `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchBotDevicesDataModel) Reset() {
	*x = SwitchBotDevicesDataModel{}
	mi := &file_infra_cache_proto_switchbot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchBotDevicesDataModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchBotDevicesDataModel) ProtoMessage() {}

func (x *SwitchBotDevicesDataModel) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cache_proto_switchbot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchBotDevicesDataModel.ProtoReflect.Descriptor instead.
func (*SwitchBotDevicesDataModel) Descriptor() ([]byte, []int) {
	return file_infra_cache_proto_switchbot_proto_rawDescGZIP(), []int{0}
}

func (x *SwitchBotDevicesDataModel) GetDevices() []*SwitchBotDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type SwitchBotDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	DeviceType    string                 `protobuf:"bytes,2,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchBotDevice) Reset() {
	*x = SwitchBotDevice{}
	mi := &file_infra_cache_proto_switchbot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchBotDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchBotDevice) ProtoMessage() {}

func (x *SwitchBotDevice) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cache_proto_switchbot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchBotDevice.ProtoReflect.Descriptor instead.
func (*SwitchBotDevice) Descriptor() ([]byte, []int) {
	return file_infra_cache_proto_switchbot_proto_rawDescGZIP(), []int{1}
}

func (x *SwitchBotDevice) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SwitchBotDevice) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

var File_infra_cache_proto_switchbot_proto protoreflect.FileDescriptor

var file_infra_cache_proto_switchbot_proto_rawDesc = string([]byte{
	0x0a, 0x21, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x25, 0x6b, 0x69, 0x6e, 0x64, 0x6c, 0x65, 0x63, 0x6c, 0x6f, 0x63, 0x6b,
	0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x62, 0x6f, 0x74, 0x22, 0x6d, 0x0a, 0x19, 0x53, 0x77,
	0x69, 0x74, 0x63, 0x68, 0x42, 0x6f, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x50, 0x0a, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x6c,
	0x65, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x62, 0x6f, 0x74,
	0x2e, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x42, 0x6f, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x4d, 0x0a, 0x0f, 0x53, 0x77, 0x69,
	0x74, 0x63, 0x68, 0x42, 0x6f, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x2d, 0x79, 0x75, 0x2f, 0x6b, 0x69, 0x6e, 0x64,
	0x6c, 0x65, 0x2d, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_infra_cache_proto_switchbot_proto_rawDescOnce sync.Once
	file_infra_cache_proto_switchbot_proto_rawDescData []byte
)

func file_infra_cache_proto_switchbot_proto_rawDescGZIP() []byte {
	file_infra_cache_proto_switchbot_proto_rawDescOnce.Do(func() {
		file_infra_cache_proto_switchbot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_infra_cache_proto_switchbot_proto_rawDesc), len(file_infra_cache_proto_switchbot_proto_rawDesc)))
	})
	return file_infra_cache_proto_switchbot_proto_rawDescData
}

var file_infra_cache_proto_switchbot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_infra_cache_proto_switchbot_proto_goTypes = []any{
	(*SwitchBotDevicesDataModel)(nil), // 0: kindleclock.infra.datamodel.switchbot.SwitchBotDevicesDataModel
	(*SwitchBotDevice)(nil),           // 1: kindleclock.infra.datamodel.switchbot.SwitchBotDevice
}
var file_infra_cache_proto_switchbot_proto_depIdxs = []int32{
	1, // 0: kindleclock.infra.datamodel.switchbot.SwitchBotDevicesDataModel.devices:type_name -> kindleclock.infra.datamodel.switchbot.SwitchBotDevice
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_infra_cache_proto_switchbot_proto_init() }
func file_infra_cache_proto_switchbot_proto_init() {
	if File_infra_cache_proto_switchbot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infra_cache_proto_switchbot_proto_rawDesc), len(file_infra_cache_proto_switchbot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_infra_cache_proto_switchbot_proto_goTypes,
		DependencyIndexes: file_infra_cache_proto_switchbot_proto_depIdxs,
		MessageInfos:      file_infra_cache_proto_switchbot_proto_msgTypes,
	}.Build()
	File_infra_cache_proto_switchbot_proto = out.File
	file_infra_cache_proto_switchbot_proto_goTypes = nil
	file_infra_cache_proto_switchbot_proto_depIdxs = nil
}
