name: Docker image build & push

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docker-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          platforms: linux/amd64
          push: false
          load: ${{ github.ref != 'refs/heads/main' }}
          tags: ghcr.io/y-yu/kindle-clock-go:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
